/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalbank.gui;
import java.sql.*;

/**
 *
 * @author lalingeman
 */
public class AccountinfoGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountinfoGUI
     */
    public AccountinfoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountIDField = new javax.swing.JTextField();
        accountFetchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        accountBalanceField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accountInterestField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accountOverdraftField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        accountTypeBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        accountDateField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        accountLastDateField = new javax.swing.JTextField();
        accountCreateButton = new javax.swing.JButton();
        accountUpdateButton = new javax.swing.JButton();
        accountDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Input Account Information");

        jLabel2.setText("ID");

        accountIDField.setText("ID(update/delete)");

        accountFetchButton.setText("Fetch");
        accountFetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountFetchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Balance");

        accountBalanceField.setText("Balance");

        jLabel4.setText("Interest");

        accountInterestField.setText("Interest");

        jLabel5.setText("Overdraft");

        accountOverdraftField.setText("Overdraft");

        jLabel6.setText("Type");

        accountTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "checking", "savings", "interest", "mma", "cod", "ira" }));

        jLabel7.setText("Date Created");

        accountDateField.setEditable(false);
        accountDateField.setText("Year-Month-Day");

        jLabel8.setText("Last Access");

        accountLastDateField.setEditable(false);
        accountLastDateField.setText("Year-Month-Day HH:MM:SS");

        accountCreateButton.setText("Create");
        accountCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCreateButtonActionPerformed(evt);
            }
        });

        accountUpdateButton.setText("Update");
        accountUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountUpdateButtonActionPerformed(evt);
            }
        });

        accountDeleteButton.setText("Delete");
        accountDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(accountCreateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDeleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountOverdraftField))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(accountIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(accountInterestField)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountFetchButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(accountTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accountLastDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(accountIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountFetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(accountInterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(accountOverdraftField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(accountTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(accountDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(accountLastDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountCreateButton)
                    .addComponent(accountUpdateButton)
                    .addComponent(accountDeleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCreateButtonActionPerformed
        String accountBalance_str = accountBalanceField.getText();
        String accountInterest_str = accountInterestField.getText();
        String accountOverdraft_str = accountOverdraftField.getText();
        String accountType_str = accountTypeBox.getSelectedItem().toString();
        
        String insertAccount = "INSERT into Accountinfo (A_Balance, A_Interest, A_Overdraft, A_AccountType, A_Date, A_LastAccess) VALUES (\'"
                +accountBalance_str+"\',\'"+accountInterest_str+"\',\'"+accountOverdraft_str+"\',\'"+accountType_str+"\',CURDATE(),NOW());";
       
        
        try{
            Statement stmt = LoginGUI.getConnection().createStatement();
            stmt.executeUpdate(insertAccount);
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
        
    
    }//GEN-LAST:event_accountCreateButtonActionPerformed

    private void accountFetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountFetchButtonActionPerformed
        String accountID_str = accountIDField.getText();
        
            try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("SELECT * from Accountinfo WHERE A_AccountID = ?");
            stmt.setString(1, accountID_str);
            ResultSet rslt = stmt.executeQuery();
            while (rslt.next()) {
                accountBalanceField.setText(rslt.getString("A_Balance"));
                accountInterestField.setText(rslt.getString("A_Interest"));
                accountOverdraftField.setText(rslt.getString("A_Overdraft"));
                accountTypeBox.setSelectedItem(rslt.getString("A_AccountType"));
                accountDateField.setText(rslt.getString("A_Date"));
                accountLastDateField.setText(rslt.getString("A_LastAccess"));
            }
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_accountFetchButtonActionPerformed

    private void accountUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountUpdateButtonActionPerformed
        String accountBalance_str = accountBalanceField.getText();
        String accountInterest_str = accountInterestField.getText();
        String accountOverdraft_str = accountOverdraftField.getText();
        String accountType_str = accountTypeBox.getSelectedItem().toString();
        String accountID_str = accountIDField.getText();
        
        String updateAccount = "UPDATE Accountinfo SET A_Balance=\'"+accountBalance_str+"\',A_Interest=\'"+accountInterest_str+"\',A_Overdraft=\'"+accountOverdraft_str+"\',A_LastAccess=NOW(),A_AccountType=\'"+accountType_str+"\' WHERE A_AccountID = ?;";
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement(updateAccount);
            stmt.setString(1, accountID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_accountUpdateButtonActionPerformed

    private void accountDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDeleteButtonActionPerformed
        String accountID_str = accountIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("DELETE from Accountinfo where A_AccountID = ?");
            stmt.setString(1, accountID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_accountDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountinfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountinfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountinfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountinfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountinfoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountBalanceField;
    private javax.swing.JButton accountCreateButton;
    private javax.swing.JTextField accountDateField;
    private javax.swing.JButton accountDeleteButton;
    private javax.swing.JButton accountFetchButton;
    private javax.swing.JTextField accountIDField;
    private javax.swing.JTextField accountInterestField;
    private javax.swing.JTextField accountLastDateField;
    private javax.swing.JTextField accountOverdraftField;
    private javax.swing.JComboBox<String> accountTypeBox;
    private javax.swing.JButton accountUpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
