/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalbank.gui;

import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;

/**
 *
 * @author kukum
 */
public class BranchInputGUI extends javax.swing.JFrame {

    /**
     * Creates new form BranchInputGUI
     */
    public BranchInputGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        branchIDField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        branchFetchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        branchNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        branchNumberField = new javax.swing.JTextField();
        branchStreetField = new javax.swing.JTextField();
        branchZipField = new javax.swing.JTextField();
        branchCityField = new javax.swing.JTextField();
        branchStateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        branchPhoneField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        branchManagerField = new javax.swing.JTextField();
        branchCreateButton = new javax.swing.JButton();
        branchUpdateButton = new javax.swing.JButton();
        branchDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Input Branch Information");

        branchIDField.setText("ID(update/delete)");

        jLabel2.setText("ID");

        branchFetchButton.setText("Fetch");
        branchFetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchFetchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        branchNameField.setText("Name");

        jLabel4.setText("Address");

        branchNumberField.setText("Number");

        branchStreetField.setText("Street");

        branchZipField.setText("ZIP");

        branchCityField.setText("City");

        branchStateField.setText("State");

        jLabel5.setText("Phone");

        branchPhoneField.setText("Phone Number");

        jLabel6.setText("Manager");

        branchManagerField.setText("Manager ID");

        branchCreateButton.setText("Create");
        branchCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchCreateButtonActionPerformed(evt);
            }
        });

        branchUpdateButton.setText("Update");
        branchUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchUpdateButtonActionPerformed(evt);
            }
        });

        branchDeleteButton.setText("Delete");
        branchDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(branchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(branchStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(branchZipField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(branchCityField)
                        .addGap(11, 11, 11)
                        .addComponent(branchStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(branchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(branchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(branchFetchButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(branchManagerField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(branchPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(branchCreateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(branchUpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(branchDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(branchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchFetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(branchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchZipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(branchManagerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchCreateButton)
                    .addComponent(branchUpdateButton)
                    .addComponent(branchDeleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchCreateButtonActionPerformed
        String branchName_str = branchNameField.getText();
        String branchNumber_str = branchNumberField.getText(); 
        String branchStreet_str = branchStreetField.getText();
        String branchZip_str = branchZipField.getText();
        String branchCity_str = branchCityField.getText();
        String branchState_str = branchStateField.getText();
        String branchPhone_str = branchPhoneField.getText();
        String branchManager_str = branchManagerField.getText();
        
        String insertBranch = "INSERT into Branch (B_BranchName, B_Number, B_Street, B_ZIP, B_City, B_State, B_Phone, B_Manager) VALUES (\'"
                +branchName_str+"\',\'"+branchNumber_str+"\',\'"+branchStreet_str+"\',\'"+branchZip_str+"\',\'"+branchCity_str+"\',\'"+branchState_str+"\',\'"+branchPhone_str+"\',\'"+branchManager_str+"\');";
        
        try{
            Statement stmt = LoginGUI.getConnection().createStatement();
            stmt.executeUpdate(insertBranch);
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_branchCreateButtonActionPerformed

    private void branchFetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchFetchButtonActionPerformed
        String branchID_str = branchIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("SELECT * from Branch WHERE B_ID = ?");
            stmt.setString(1, branchID_str);
            ResultSet rslt = stmt.executeQuery();
            while (rslt.next()) {
                branchNameField.setText(rslt.getString("B_BranchName"));
                branchNumberField.setText(rslt.getString("B_Number"));
                branchStreetField.setText(rslt.getString("B_Street"));
                branchZipField.setText(rslt.getString("B_ZIP"));
                branchCityField.setText(rslt.getString("B_City"));
                branchStateField.setText(rslt.getString("B_State"));
                branchPhoneField.setText(rslt.getString("B_Phone"));
                branchManagerField.setText(rslt.getString("B_Manager"));
            }
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_branchFetchButtonActionPerformed

    private void branchUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchUpdateButtonActionPerformed
        String branchName_str = branchNameField.getText();
        String branchNumber_str = branchNumberField.getText(); 
        String branchStreet_str = branchStreetField.getText();
        String branchZip_str = branchZipField.getText();
        String branchCity_str = branchCityField.getText();
        String branchState_str = branchStateField.getText();
        String branchPhone_str = branchPhoneField.getText();
        String branchManager_str = branchManagerField.getText();
        String branchID_str = branchIDField.getText();
        
        String updateBranch = "UPDATE Branch SET B_BranchName=\'"+branchName_str+"\',B_Number=\'"+branchNumber_str+"\',B_Street=\'"+branchStreet_str+"\',B_ZIP=\'"+branchZip_str+"\',B_City=\'"+branchCity_str+"\',B_State=\'"+branchState_str+"\',B_Phone=\'"+branchPhone_str+"\',B_Manager=\'"+branchManager_str+"\' WHERE B_ID = ?;";
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement(updateBranch);
            stmt.setString(1, branchID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_branchUpdateButtonActionPerformed

    private void branchDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchDeleteButtonActionPerformed
        String branchID_str = branchIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("DELETE from Branch where B_ID = ?");
            stmt.setString(1, branchID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_branchDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchInputGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchCityField;
    private javax.swing.JButton branchCreateButton;
    private javax.swing.JButton branchDeleteButton;
    private javax.swing.JButton branchFetchButton;
    private javax.swing.JTextField branchIDField;
    private javax.swing.JTextField branchManagerField;
    private javax.swing.JTextField branchNameField;
    private javax.swing.JTextField branchNumberField;
    private javax.swing.JTextField branchPhoneField;
    private javax.swing.JTextField branchStateField;
    private javax.swing.JTextField branchStreetField;
    private javax.swing.JButton branchUpdateButton;
    private javax.swing.JTextField branchZipField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
