/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalbank.gui;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
/**
 *
 * @author lalingeman
 */
public class EmployeeInputGUI extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeInputGUI
     */
    public EmployeeInputGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        mNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dobDay = new javax.swing.JTextField();
        dobMonth = new javax.swing.JTextField();
        dobYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressNumber = new javax.swing.JTextField();
        addressStreet = new javax.swing.JTextField();
        addressZip = new javax.swing.JTextField();
        addressCity = new javax.swing.JTextField();
        addressState = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phoneNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        branchID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dojDay = new javax.swing.JTextField();
        dojMonth = new javax.swing.JTextField();
        dojYear = new javax.swing.JTextField();
        empInfoSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        fetchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Employee Information");

        jLabel2.setText("Name");

        fNameField.setText("First");

        mNameField.setText("Middle");

        lNameField.setText("Last");

        jLabel3.setText("DateOfBirth");

        dobDay.setText("Day");

        dobMonth.setText("Month");

        dobYear.setText("Year");

        jLabel4.setText("Address");

        addressNumber.setText("Number");

        addressStreet.setText("Street");

        addressZip.setText("ZIP");

        addressCity.setText("City");

        addressState.setText("State");

        jLabel5.setText("Phone");

        phoneNum.setText("Phone Number");

        jLabel6.setText("Title");

        title.setText("Job Title");

        jLabel7.setText("Salary");

        salary.setText("Salary");

        jLabel8.setText("Branch");

        branchID.setText("Branch ID");

        jLabel9.setText("DateOfJoin");

        dojDay.setText("Day");

        dojMonth.setText("Month");

        dojYear.setText("Year");

        empInfoSubmit.setText("Create");
        empInfoSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empInfoSubmitActionPerformed(evt);
            }
        });

        jLabel10.setText("Username");

        username.setText("Username");

        jLabel12.setText("Password");

        password.setText("Password");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        idField.setText("ID(update/delete)");

        fetchButton.setText("Fetch");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(salary)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(branchID, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressZip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressState, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dojMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dojYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(dobYear, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dobDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(66, 66, 66)
                                .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(dojDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(dobMonth))
                                .addGap(108, 108, 108))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fetchButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(empInfoSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dobDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dojDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dojMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dojYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(branchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empInfoSubmit)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empInfoSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empInfoSubmitActionPerformed
        // Save text
        String fName_str = fNameField.getText(); // not null
        String mName_str = mNameField.getText();
        String lName_str = lNameField.getText(); // not null
        String dobDay_str = dobDay.getText(); // not null
        String dobMonth_str = dobMonth.getText(); // not null
        String dobYear_str = dobYear.getText(); // not null
        String dojDay_str = dojDay.getText(); // not null
        String dojMonth_str = dojMonth.getText(); // not null
        String dojYear_str = dojYear.getText(); // not null
        String adNum_str = addressNumber.getText();
        String adStreet_str = addressStreet.getText();
        String adZIP_str = addressZip.getText();
        String adCity_str = addressCity.getText();
        String adState_str = addressState.getText();
        String title_str = title.getText();
        String phone_str = phoneNum.getText();
        String salary_str = salary.getText();
        String branchID_str = branchID.getText();
        if (branchID_str.equals("")) {
            branchID_str = null;
        }
        String username_str = username.getText();
        String password_str = String.valueOf(password.getPassword());
        
        
        //convert salary string to double
        double salary_dbl = Double.parseDouble(salary_str);
        
        //convert branchID string to int
        int branchID_int = 1;
        if (branchID_str != null) {
            branchID_int = Integer.parseInt(branchID_str);
        }
        
        //convert DOB & DOJ into date format
        String dob = dobYear_str + "-" + dobMonth_str + "-" + dobDay_str;
        String doj = dojYear_str + "-" + dojMonth_str + "-" + dojDay_str;
        
        //insert statement
        String insertEmp = "INSERT INTO Employee (E_FName, E_MName, E_LName, E_Street, E_ZIP, E_City, E_State, E_Phone, E_Title, E_Salary, E_BranchID, E_DOB, E_DateOfJoin, E_Username, E_Number) VALUES (\'"
                        +fName_str+"\',\'"+mName_str+"\',\'"+lName_str+"\',\'"+adStreet_str+"\',\'"+adZIP_str+"\',\'"+adCity_str+"\',\'"+adState_str+"\',\'"+phone_str+"\',\'"+title_str+"\',"+salary_dbl+","+branchID_int+",\'"+dob+"\',\'"+doj+"\',\'"+username_str+"\',\'"+adNum_str+"\');"
                + "INSERT INTO Login (LG_Username, LG_Password) values (\'"+username_str+"\',\'"+password_str+"\');";
        
        
        //enter into DB
        try{
            Statement stmt = LoginGUI.getConnection().createStatement();
            stmt.executeUpdate(insertEmp);
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
        
    }//GEN-LAST:event_empInfoSubmitActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Save text
        String fName_str = fNameField.getText(); // not null
        String mName_str = mNameField.getText();
        String lName_str = lNameField.getText(); // not null
        String dobDay_str = dobDay.getText(); // not null
        String dobMonth_str = dobMonth.getText(); // not null
        String dobYear_str = dobYear.getText(); // not null
        String dojDay_str = dojDay.getText(); // not null
        String dojMonth_str = dojMonth.getText(); // not null
        String dojYear_str = dojYear.getText(); // not null
        String adNum_str = addressNumber.getText();
        String adStreet_str = addressStreet.getText();
        String adZIP_str = addressZip.getText();
        String adCity_str = addressCity.getText();
        String adState_str = addressState.getText();
        String title_str = title.getText();
        String phone_str = phoneNum.getText();
        String salary_str = salary.getText();
        String branchID_str = branchID.getText();
        if (branchID_str.equals("")) {
            branchID_str = null;
        }
        String username_str = username.getText();
        String password_str = String.valueOf(password.getPassword());
        
        
        //convert salary string to double
        double salary_dbl = Double.parseDouble(salary_str);
        
        //convert branchID string to int
        int branchID_int = 1;
        if (branchID_str != null) {
            branchID_int = Integer.parseInt(branchID_str);
        }
        
        //convert DOB & DOJ into date format
        String dob = dobYear_str + "-" + dobMonth_str + "-" + dobDay_str;
        String doj = dojYear_str + "-" + dojMonth_str + "-" + dojDay_str;
        
        int empID_int = Integer.parseInt(idField.getText());
        
        String updateEmp = "UPDATE Employee SET E_Fname=\'"+fName_str+"\',E_Mname=\'"+mName_str+"\',E_Lname=\'"+lName_str+"\',E_Street=\'"+adStreet_str+"\',E_ZIP=\'"+adZIP_str+"\',E_City=\'"+adCity_str+"\',E_State=\'"+adState_str+"\',E_Phone=\'"+phone_str+"\',E_Title=\'"+title_str+"\',E_Salary="+salary_dbl+",E_BranchID="+branchID_int+",E_DOB=\'"+dob+"\',E_DateOfJoin=\'"+doj+"\',E_Username=\'"+username_str+"\',E_Number=\'"+adNum_str+"\' WHERE E_ID=?;";
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement(updateEmp);
            stmt.setInt(1, empID_int);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        // Write current values
        int empID_int = Integer.parseInt(idField.getText());
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("SELECT * from EMPLOYEE where E_ID = ?");
            stmt.setInt(1, empID_int);
            ResultSet rslt = stmt.executeQuery();
            while (rslt.next()) {
                fNameField.setText(rslt.getString("E_FName"));
                mNameField.setText(rslt.getString("E_MName"));
                lNameField.setText(rslt.getString("E_LName"));
            
                LocalDate dobLD = rslt.getDate("E_DOB").toLocalDate();
                dobDay.setText(Integer.toString(dobLD.getDayOfMonth()));
                dobMonth.setText(Integer.toString(dobLD.getMonthValue()));
                dobYear.setText(Integer.toString(dobLD.getYear()));
            
                LocalDate dojLD = rslt.getDate("E_DateOfJoin").toLocalDate();
                dojDay.setText(Integer.toString(dojLD.getDayOfMonth()));
                dojMonth.setText(Integer.toString(dojLD.getMonthValue()));
                dojYear.setText(Integer.toString(dojLD.getYear()));
            
                addressNumber.setText(rslt.getString("E_Number"));
                addressStreet.setText(rslt.getString("E_Street"));
                addressZip.setText(rslt.getString("E_ZIP"));
                addressCity.setText(rslt.getString("E_City"));
                addressState.setText(rslt.getString("E_State"));
                title.setText(rslt.getString("E_Title"));
                phoneNum.setText(rslt.getString("E_Phone"));
                salary.setText(rslt.getString("E_Salary"));
                branchID.setText(rslt.getString("E_BranchID"));
                username.setText(rslt.getString("E_Username"));
                password.setText("xxx");
            }
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_fetchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int empID_int = Integer.parseInt(idField.getText());
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("DELETE from EMPLOYEE where E_ID = ?");
            stmt.setInt(1, empID_int);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeInputGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeInputGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressCity;
    private javax.swing.JTextField addressNumber;
    private javax.swing.JTextField addressState;
    private javax.swing.JTextField addressStreet;
    private javax.swing.JTextField addressZip;
    private javax.swing.JTextField branchID;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dobDay;
    private javax.swing.JTextField dobMonth;
    private javax.swing.JTextField dobYear;
    private javax.swing.JTextField dojDay;
    private javax.swing.JTextField dojMonth;
    private javax.swing.JTextField dojYear;
    private javax.swing.JButton empInfoSubmit;
    private javax.swing.JTextField fNameField;
    private javax.swing.JButton fetchButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lNameField;
    private javax.swing.JTextField mNameField;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField title;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
