/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalbank.gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author kukum
 */
public class PerformanceGUI extends javax.swing.JFrame {

    /**
     * Creates new form PerformanceGUI
     */
    public PerformanceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        perfIDField = new javax.swing.JTextField();
        perfFetchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        perfEmpIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        perfDateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perfRecordField = new javax.swing.JTextArea();
        perfCreateButton = new javax.swing.JButton();
        perfUpdateButton = new javax.swing.JButton();
        perfDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Input Performance Information");

        jLabel2.setText("Performance ID");

        perfIDField.setText("ID");

        perfFetchButton.setText("Fetch");
        perfFetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfFetchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee ID");

        perfEmpIDField.setText("Employee ID");

        jLabel4.setText("Date");

        perfDateField.setText("Date (yyyy-mm-dd)");

        jLabel5.setText("Record");

        perfRecordField.setColumns(20);
        perfRecordField.setRows(5);
        perfRecordField.setText("Record");
        jScrollPane1.setViewportView(perfRecordField);

        perfCreateButton.setText("Create");
        perfCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfCreateButtonActionPerformed(evt);
            }
        });

        perfUpdateButton.setText("Update");
        perfUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfUpdateButtonActionPerformed(evt);
            }
        });

        perfDeleteButton.setText("Delete");
        perfDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(perfDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perfIDField)
                                    .addComponent(perfEmpIDField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(perfFetchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(perfCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perfUpdateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perfDeleteButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(perfFetchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(perfEmpIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(perfDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfCreateButton)
                    .addComponent(perfUpdateButton)
                    .addComponent(perfDeleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfCreateButtonActionPerformed
        String perfEmpID_str = perfEmpIDField.getText();
        String perfDate_str = perfDateField.getText();
        String perfRecord_str = perfRecordField.getText();
        
        String insertPerf = "INSERT into Performance (P_Employee, P_Date, P_Record) values (\'"+perfEmpID_str+"\',\'"+perfDate_str+"\',\'"+perfRecord_str+"\');";
        
        try{
            Statement stmt = LoginGUI.getConnection().createStatement();
            stmt.executeUpdate(insertPerf);
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_perfCreateButtonActionPerformed

    private void perfFetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfFetchButtonActionPerformed
        String perfID_str = perfIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("SELECT * from Performance WHERE P_ID = ?");
            stmt.setString(1, perfID_str);
            ResultSet rslt = stmt.executeQuery();
            while (rslt.next()) {
                perfEmpIDField.setText(rslt.getString("P_Employee"));
                perfDateField.setText(rslt.getString("P_Date"));
                perfRecordField.setText(rslt.getString("P_Record"));
            }
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_perfFetchButtonActionPerformed

    private void perfUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfUpdateButtonActionPerformed
        String perfID_str = perfIDField.getText();
        String perfEmpID_str = perfEmpIDField.getText();
        String perfDate_str = perfDateField.getText();
        String perfRecord_str = perfRecordField.getText();
        
        String updatePerf = "UPDATE Performance SET P_Employee=\'"+perfEmpID_str+"\',P_Date=\'"+perfDate_str+"\',P_Record=\'"+perfRecord_str+"\' WHERE P_ID = ?;";
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement(updatePerf);
            stmt.setString(1, perfID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_perfUpdateButtonActionPerformed

    private void perfDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfDeleteButtonActionPerformed
        String perfID_str = perfIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("DELETE from Performance where P_ID = ?");
            stmt.setString(1, perfID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }  
    }//GEN-LAST:event_perfDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerformanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerformanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerformanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerformanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerformanceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton perfCreateButton;
    private javax.swing.JTextField perfDateField;
    private javax.swing.JButton perfDeleteButton;
    private javax.swing.JTextField perfEmpIDField;
    private javax.swing.JButton perfFetchButton;
    private javax.swing.JTextField perfIDField;
    private javax.swing.JTextArea perfRecordField;
    private javax.swing.JButton perfUpdateButton;
    // End of variables declaration//GEN-END:variables
}
