/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalbank.gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author lalingeman
 */
public class TransactioninfoGUI extends javax.swing.JFrame {

    /**
     * Creates new form TransactioninfoGUI
     */
    public TransactioninfoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        transIDField = new javax.swing.JTextField();
        transFetchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        transAccountIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        transModeBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        transBalanceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        transDateField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        transTypeBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        transRemarksField = new javax.swing.JTextField();
        transCreateButton = new javax.swing.JButton();
        transUpdateButton = new javax.swing.JButton();
        transDeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Enter Transaction Information");

        jLabel2.setText("ID");

        transIDField.setText("ID(update/delete)");

        transFetchButton.setText("Fetch");
        transFetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transFetchButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Account ID");

        transAccountIDField.setText("Account ID");

        jLabel4.setText("Mode");

        transModeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "check", "card", "other" }));

        jLabel5.setText("Balance");

        transBalanceField.setText("Balance");

        jLabel6.setText("Date");

        transDateField.setText("Date");

        jLabel7.setText("Type");

        transTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "credit", "debit" }));

        jLabel8.setText("Remarks");

        transRemarksField.setText("Remarks");

        transCreateButton.setText("Create");
        transCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transCreateButtonActionPerformed(evt);
            }
        });

        transUpdateButton.setText("Update");
        transUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transUpdateButtonActionPerformed(evt);
            }
        });

        transDeleteButton.setText("Delete");
        transDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transAccountIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transFetchButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(transModeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transDateField))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(transRemarksField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(transCreateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transDeleteButton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transFetchButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(transAccountIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(transModeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(transBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(transDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transRemarksField)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(transTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transCreateButton)
                    .addComponent(transUpdateButton)
                    .addComponent(transDeleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transCreateButtonActionPerformed
        String transAccountID_str = transAccountIDField.getText();
        String transMode_str = transModeBox.getSelectedItem().toString();
        String transBalance_str = transBalanceField.getText();
        String transDate_str = transDateField.getText();
        String transType_str = transTypeBox.getSelectedItem().toString();
        String transRemarks_str = transRemarksField.getText();
        
        String insertTrans = "INSERT into Transactioninfo (T_AccountID, T_Mode, T_Balance, T_Date, T_Type, T_Remarks) values (\'"
                +transAccountID_str+"\',\'"+transMode_str+"\',\'"+transBalance_str+"\',\'"+transDate_str+"\',\'"+transType_str+"\',\'"+transRemarks_str+"\');";
        
        try{
            Statement stmt = LoginGUI.getConnection().createStatement();
            stmt.executeUpdate(insertTrans);
        } 
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_transCreateButtonActionPerformed

    private void transFetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transFetchButtonActionPerformed
        String transID_str = transIDField.getText();
        
            try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("SELECT * from Transactioninfo WHERE T_TransactionID = ?");
            stmt.setString(1, transID_str);
            ResultSet rslt = stmt.executeQuery();
            while (rslt.next()) {
                transAccountIDField.setText(rslt.getString("T_AccountID"));
                transModeBox.setSelectedItem(rslt.getString("T_Mode"));
                transBalanceField.setText(rslt.getString("T_Balance"));
                transDateField.setText(rslt.getString("T_Date"));
                transTypeBox.setSelectedItem(rslt.getString("T_Type"));
                transRemarksField.setText(rslt.getString("T_Remarks"));
            }
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class not found");
        }
        catch (SQLException s) {
            System.out.println("SQL exception " + s.getMessage());
        }
    }//GEN-LAST:event_transFetchButtonActionPerformed

    private void transUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transUpdateButtonActionPerformed
        String transAccountID_str = transAccountIDField.getText();
        String transMode_str = transModeBox.getSelectedItem().toString();
        String transBalance_str = transBalanceField.getText();
        String transDate_str = transDateField.getText();
        String transType_str = transTypeBox.getSelectedItem().toString();
        String transRemarks_str = transRemarksField.getText();
        String transID_str = transIDField.getText();
        
        String updateTrans = "UPDATE Transactioninfo SET T_AccountID=\'"+transAccountID_str+"\',T_Mode=\'"+transMode_str+"\',T_Balance=\'"+transBalance_str+"\',T_Date=\'"+transDate_str+"\',T_Type=\'"+transType_str+"\',T_Remarks=\'"+transRemarks_str+"\' where T_TransactionID = ?;";
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement(updateTrans);
            stmt.setString(1, transID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_transUpdateButtonActionPerformed

    private void transDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transDeleteButtonActionPerformed
        String transID_str = transIDField.getText();
        
        try {
            PreparedStatement stmt = LoginGUI.getConnection().prepareStatement("DELETE from Transactioninfo where T_TransactionID = ?");
            stmt.setString(1, transID_str);
            stmt.executeUpdate();
        }
        catch (SQLException s) {
            System.out.println("SQL Exception " + s.getMessage());
        }
        catch (ClassNotFoundException e) {
            System.out.println("Class Exception " + e.getMessage());
        }
    }//GEN-LAST:event_transDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactioninfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactioninfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactioninfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactioninfoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactioninfoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField transAccountIDField;
    private javax.swing.JTextField transBalanceField;
    private javax.swing.JButton transCreateButton;
    private javax.swing.JTextField transDateField;
    private javax.swing.JButton transDeleteButton;
    private javax.swing.JButton transFetchButton;
    private javax.swing.JTextField transIDField;
    private javax.swing.JComboBox<String> transModeBox;
    private javax.swing.JTextField transRemarksField;
    private javax.swing.JComboBox<String> transTypeBox;
    private javax.swing.JButton transUpdateButton;
    // End of variables declaration//GEN-END:variables
}
